lesson_12/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('user/', include('user.urls')),
    *staticfiles_urlpatterns(),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

]

market/urls.py
from django.urls import path

from market import views

app_name = 'market'

urlpatterns = [
    path('', views.list, name='list'),
    path('view/<item_id>/', views.item, name='item'),
    path('add/', views.add, name='add'),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup')
]

market/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User



class Brand(models.Model):
    name = models.CharField(max_length=50)
    rating = models.FloatField(max_length=5)

    def __str__(self):
        return f'{self.pk}-{self.name}({self.rating})'


class Tags(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)


class Wallpaper(models.Model):
    slug = models.SlugField(unique=True, allow_unicode=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    price = models.FloatField(null=True, blank=True)
    available = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)
    description = models.TextField()
    cover = models.ImageField(blank=True, null=True, default='placeholder.png')
    tags = models.ManyToManyField(Tags)
    creator = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.SET_NULL)
    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['price', 'create_at']

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('market:item', kwargs={'item_id': self.slug})

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = f'{str(self.name).lower().replace(" ", "-").replace("/", "-")[:20]}-{self.color}'
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.pk} - {self.brand} - {self.name}'

user/models.py
from django.db import models

# Create your models here.

market/forms.py
from django import forms

from market.models import Wallpaper


class WallpaperForm(forms.ModelForm):
    class Meta:
        model = Wallpaper
        fields = ('name', 'brand', 'tags', 'color', 'price', 'available', 'quantity', 'description', 'cover')

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User


class ExtendedUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        label="First Name",
        widget=forms.TextInput
    )
    last_name = forms.CharField(
        label="Last Name",
        widget=forms.TextInput
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

market/views.py
from django.shortcuts import render, redirect

from market.forms import WallpaperForm
from market.models import Wallpaper


def list(request):
    wallpapers = Wallpaper.objects.all()
    return render(request,
                  'market/wallpapers.html',
                  context={'wallpapers': wallpapers})


def item(request, item_id):
    wallpaper = Wallpaper.objects.get(slug=item_id)
    tags = wallpaper.tags.all()
    return render(request,
                  'market/wallpaper.html',
                  context={'wallpaper': wallpaper, 'tags': tags})


def add(request):
    if request.method == 'POST':
        form = WallpaperForm(request.POST, request.FILES)
        if form.is_valid():
            new_wallpaper = form.save(commit=False)
            new_wallpaper.creator = request.user
            new_wallpaper.save()
            form.save_m2m()
            return redirect('market:item', item_id=new_wallpaper.slug)
        return render(request, 'market/new_wallpaper.html', context={'form': form})
    form = WallpaperForm()
    return render(request, 'market/new_wallpaper.html', context={'form': form})

user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.
from user.forms import ExtendedUserCreationForm


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('market:list')
        return render(request, 'user/login.html', context={'form': form})
    form = AuthenticationForm()
    return render(request, 'user/login.html', context={'form': form})


def logout_view(request):
    logout(request)
    return redirect('user:login')


def signup_view(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login')
        return render(request, 'user/signin.html', context={'form': form})
    form = ExtendedUserCreationForm()
    return render(request, 'user/signin.html', context={'form': form})

market/templates/market/new_wallpaper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add wallpaper</title>
</head>
<body>
<form action="{% url 'market:add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Додать">
</form>
</body>
</html>

market/templates/market/wallpaper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallpeper</title>
</head>
<body>
<a href="{% url 'market:list' %}"><- Return</a>

<h1>Id: {{ wallpaper.pk }}</h1>
<h1>Name: {{ wallpaper.name }}</h1>
<h2>Brand: {{ wallpaper.brand.name }}</h2>
<h3>Price: {{ wallpaper.price }}</h3>
<h3>Added: {{ wallpaper.create_at }}</h3>

<h3>Характеристики: </h3>
{% if tags %}
<ul>
    {% for tag in tags %}
    <li id="{{tag.name}}-{{tag.pk}}">{{tag.name}}</li>
    {% endfor %}
</ul>
{% else %}
<p>відсутні</p>
{% endif %}
<img src="{{ wallpaper.cover.url }}"/>
</body>
</html>

market/templates/market/wallpapers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallpepers</title>
</head>
<body>
{% for wallpaper in wallpapers %}
<a href="{{ wallpaper.get_absolute_url }}">{{ wallpaper }}</a>
{% endfor %}
</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="{% url 'user:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Логін">
</form>
</body>
</html>

user/templates/user/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<form action="{% url 'user:signup' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Створити">
</form>
</body>
</html>